
# Set statusline
set -g status-right "%H:%M"

# Start index at 1
set -g base-index 1

# Enable RGB
set-option -sa terminal-features ",xterm*:RGB"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# No bells
set -g bell-action none

# Turn the mouse on
set -g mouse on

# Toggle between largest and smallest window
bind F set -w window-size

# Set vim keys
set-window-option -g mode-keys vi

# Set copy and paste
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Set custom prefix
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Go to last window with double prefix
bind C-Space last-window

# Set focus-events for neovim
set-option -g focus-events on

# Create new window in curret directory
bind c new-window -c "#{pane_current_path}"

# Move between panes using vim motions
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
